name: instant_rpc
version: 0.1.2
author: Graciliano Monteiro Passos <gracilianomp@gmail.com>
description: A simple Dart RPC over HTTP.
homepage: https://github.com/UpLibs/instant_rpc
dependencies:
  worker: '>=0.3.7 <0.3.8'
